# Generated by Django 4.1.7 on 2023-02-21 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, unique=True)),
                ('description', models.CharField(default='', max_length=300)),
                ('price', models.DecimalField(decimal_places=2, default=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='BurgerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('order_number', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('burgers', models.ManyToManyField(to='burgers.burger')),
            ],
        ),
        migrations.CreateModel(
            name='BurgerOrderBurger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burgers.burger')),
                ('burger_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burgers.burgerorder')),
            ],
        ),
    ]
