# Generated by Django 4.1.7 on 2023-02-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='burger',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='burger',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='burgers',
            field=models.CharField(default='', max_length=200),
        ),
    ]
